# Generated by Django 2.2.4 on 2019-08-31 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepost_articletag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
