# Generated by Django 2.2.5 on 2019-09-18 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_form',
            new_name='user_from',
        ),
    ]
